name: marenero
description: .

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Dart
  http: ^0.13.3

  # Firebase
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.5

  # Spotify
  spotify_sdk:
  flutter_dotenv: ^4.0.0-nullsafety.0

  # Third party
  google_fonts: ^2.0.0
  pinput: ^1.2.0
  auto_size_text: 3.0.0-nullsafety.0
  uuid: ^3.0.4
  tap_debouncer: ^2.0.0
  loading_overlay: ^0.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
