name: marenero
description: .

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  cupertino_icons: any

  # Dart
  http: any

  # Firebase
  firebase_core: any
  cloud_firestore: any
  firebase_analytics: any

  # Spotify
  spotify_sdk: any
  flutter_dotenv: any

  # Third party
  google_fonts: any
  pinput: any
  auto_size_text: any
  uuid: any
  tap_debouncer: any
  loading_overlay: any
  web_browser_detect: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
